version: 0.1

phases:

  install:
    commands:
      - echo Get dependencies...
      - go get -t -d -v ./...

  build:
    commands:

      # Build our application
      - echo Build application...
      - go build -v -o app

artifacts:
  files:
    - app